// generated by stringer -type=State; DO NOT EDIT

package builds

import "fmt"

const _State_name = "WaitingBuildingPushingCompleteFailed"

var _State_index = [...]uint8{0, 7, 15, 22, 30, 36}

func (i State) String() string {
	if i < 0 || i+1 >= State(len(_State_index)) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
